### ISSUE TITLE
MISP 2.4.97

### ISSUE THREAD

**Issue by adulau** [DCSO/MISP-dockerized#39]
Any plan to make the 2.4.97 default? Thanks a lot.

**Comment by 8ear** [comment]
Hi,
Yeah, we're working on it. But since we changed the base from ubuntu to debian. But we still need some time to do some testing.

**Comment by adulau** [comment]
Thank you for the feedback. I was wondering if we should make it official under the MISP project organisation at some point (as discussed during hack.lu).

**Comment by 8ear** [comment]
Hi,
currently the new 2.4.97 container is in build process. 
See: https://travis-ci.org/DCSO/MISP-dockerized-server/jobs/456047150

If it is ready you can use it with the following tag command:
dcso/misp-dockerized-server:2.4.97-dev

As soon as i've added the change to the main repository, the container will also be available on the following tag:
dcso/misp-dockerized-server:2.4.97

This time the new version requires a lot of time, because we switched the base from ubuntu 18.04 to debian stretch and we moved our ansible script tasks into the container.
